Add "Remote Persistent Workers"
bazelbuild/proposals pull request #219
Opened 2021-03-06 00:27 UTC by ulfjack

2021-03-08 08:34 UTC, lberki approved these changes

2021-03-08 08:34 UTC, lberki commented on designs/2021-03-06-remote-persistent-workers.md
> +  - larsrc-google
Mind adding github.com/coeuvre (chiwang@google.com) as a reviewer?

2021-03-08 08:35 UTC, lberki requested changes
Mind adding github.com/coeuvre (chiwang@google.com) as a reviewer also?

2021-03-08 08:35 UTC, lberki commented
/cc @philwo

2021-03-08 08:35 UTC, larsrc-google commented on designs/2021-03-06-remote-persistent-workers.md
> +It would be trivial to extend the prototype to set a `persistentWorkerProtocol`
The worker key already contains the protocol format used and whether it's (supposed to be) a multiplex worker. Do you ignore those?

2021-03-09 20:04 UTC, ulfjack commented
Added @coeuvre as a reviewer.

2021-03-10 08:43 UTC, lberki approved these changes

2021-03-10 08:43 UTC, merged